# Generated by Django 4.2.23 on 2025-09-21 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_alter_usercourse_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='introduce',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lessonprogress',
            name='status',
            field=models.CharField(choices=[('NOT_STARTED', 'Chưa bắt đầu'), ('IN_PROGRESS', 'Đang học'), ('COMPLETED', 'Hoàn thành')], default='NOT_STARTED', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='lessonprogress',
            unique_together={('lesson', 'user')},
        ),
    ]
